### ISSUE TITLE
Team members list

### ISSUE THREAD

**Issue by TatianaFomina** [codex-team/notes.web#132]
Make figma mockups for team members list components on note settings page. 

Now they look like this:

![Image](https://github.com/codex-team/notes.web/assets/31101125/db64c6e4-7d19-48c7-9f67-eadcf7d6aa86)

- [ ] #134

**Comment by neSpecc** [comment]
https://www.figma.com/file/YmJc2Vqmev25xZgXic5bjL/NoteX-Design-System-(Inter)?type=design&node-id=1668-635&mode=design&t=pXf6ClYZc8bEcP9y-4
