### ISSUE TITLE
/join/ route handler on web part

### ISSUE THREAD

**Issue by e11sy** [codex-team/notes.web#183]
## Problem:
Now, when we visit join route specified on note-settings page, it returns 404 status code, and user does not join team of the note
## Solution
Create /join/ route handler on web part

**Comment by neSpecc** [comment]
<img width="1211" alt="image" src="https://github.com/codex-team/notes.web/assets/3684889/b2757d1d-273e-4fb2-bd7e-b02eae469bc2">


https://www.figma.com/file/oV9NY9Ia6AshcYX3YaBp8g/CodeX-Notes?type=whiteboard&node-id=0-1&t=68XbsHxyWhuLz1dH-0
