### ISSUE TITLE
Use Tabbar in app header

### ISSUE THREAD

**Issue by neSpecc** [codex-team/notes.web#205]
- [x] Header should use Tabbar component
- [x] Tabbar should be responsive. 
  - [x] When many tabs are existing, the Tab text should be wrapped with `...` symbol. Like in browser tabs
  - [x] Tab should have a min-width: paddingLeft + Icon size + paddingRight
  - [x] When there are many tabs and all of them reached min-width, tabbar should be scrollable
- [x] Opened Page should be displayed in a Tabbar: either Note, Note Settings, User Settings, Marketplace, etc
- [x] Current Page should be highlighted in a Tabbar
- [x] All opened pages should remain in tabbar even after refreshing a page

**Comment by e11sy** [comment]
solved in series of PR: 
- #219 
- #222 
- #226 
- #227
