### ISSUE TITLE
[ Bug ] Note settings title in tabbar duplicates note title

### ISSUE THREAD

**Issue by e11sy** [codex-team/notes.web#269]
## Problem 
For now Note settings title in tabbar duplicates note title 
![image](https://github.com/user-attachments/assets/5b7d76be-9e2e-482f-910e-d9786b22dc59)

## Expected behaviour
When note settings just opened it's title should be just `Note settings`
After note is loaded Note settings title should be updated to `Note settings ({ Note title })`

## Solution
Note settings page should use `UseHeader()` and `UseNote()` application services
- Add watcher for `noteTitle` variable from `UseNote()` app service (it should be on `NoteSettings` page)
- Use `patchOpenedPageByUrl()` method from `UseHeader()` app service for patching title of note settings in tabbar

**Comment by dependentmadani** [comment]
This issue has been fixed.
